const OK_CODE = 200;
const CREATE_CODE = 201;
const BAD_REQUEST_ERROR_CODE = 400;
const INCORRECT_EMAIL_PASSWORD_ERROR_CODE = 401;
const NO_ACCESS_ERROR_CODE = 403;
const NOT_FOUND_ERROR_CODE = 404;
const CONFLICT_ERROR_CODE = 409;
const MONGO_DUPLICATE_ERROR_CODE = 11000;
const DEFAULT_ERROR_CODE = 500;

module.exports = {
  OK_CODE,
  CREATE_CODE,
  BAD_REQUEST_ERROR_CODE,
  INCORRECT_EMAIL_PASSWORD_ERROR_CODE,
  NOT_FOUND_ERROR_CODE,
  CONFLICT_ERROR_CODE,
  MONGO_DUPLICATE_ERROR_CODE,
  DEFAULT_ERROR_CODE,
  NO_ACCESS_ERROR_CODE,
};
